
coverage:
  status:
    project:
      default:
        target: auto
      method:
        target: auto
        flags:
          - method
      unit:
        target: auto
        flags:
          - unit
      flag_coverage_not_uploaded_behavior: pass 
flags:
  method:
    paths:
      - cclib/method/
    carryforward: true
  unit:
    paths:
      - cclib/io/
      - cclib/parser/
      - cclib/bridge/
    carryforward: true
