
coverage:
  status:
    project:
      default:
        target: auto
      method:
        target: auto
        flags:
          - method
      unit:
        target: auto
        flags:
          - unit

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false  
  require_base: yes
  require_head: yes       
  branches: null

flags:
  method:
    paths:
      - cclib/method/
    carryforward: true
  unit:
    paths:
      - cclib/io/
      - cclib/parser/
      - cclib/bridge/
    carryforward: true
