[tool.ruff]
# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
    # User Specific Directories, which currently not tested
    "test",
    "doc"

]

# Same as Black.
line-length = 100
indent-width = 4

# Assume Python 3.8
target-version = "py38"

ignore = ["ANN101"] # annotations for self
src = ["cclib"]

# select = ["ALL"]


[tool.ruff.per-file-ignores]
"test/test*.py" = [
    "PLR2004", # magic value comparison
    "S101",    # use of assert detected
    "TCH002",  # third party import (for pytest)
]



[tool.ruff.isort]

known-first-party = ["cclib"]
force-single-line = true
lines-between-types = 1
lines-after-imports = 2


[tool.ruff.lint]
# Enable Pyflakes (`F`) and a subset of the pycodestyle (`E`)  codes by default.
select = []
ignore = []

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"

[tool.mypy]
warn_redundant_casts = true
warn_return_any = true
warn_unreachable = true

scripts_are_modules = true
warn_unused_configs = true

# Disallow dynamic typing
# disallow_any_unimported = true
# disallow_any_expr = true
# disallow_any_decorated = true
# disallow_any_explicit = true
# disallow_any_generics = true
# disallow_subclassing_any = true

# Untyped definitions and calls
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
# check_untyped_defs = true
disallow_untyped_decorators = true

# None and optional handling

# Configuring warnings
warn_unused_ignores = true
#warn_return_any = true
#warn_unreachable = true

# Miscellaneous
#warn_unused_configs = true

[[tool.mypy.overrides]]
module = [
    "Bio.PDB.Atom",
    "Bio.PDB.Superimposer",
    "PyQt4",
    "PyQuante.CGBF",
    "PyQuante.Molecule",
    "PyQuante.hartree_fock",
    "ase",
    "ase.calculators.calculator",
    "ase.calculators.emt",
    "ase.io.trajectory",
    "h5py",
    "horton",
    "horton.io.iodata",
    "iodata",
    "iodata.api",
    "iodata.orbitals",
    "openbabel",
    "openbabel.pybel",
    "periodictable",
    "psi4",
    "psi4.core",
    "pybel",
    "pyquante2",
    "pyscf",
    "pyvtk",
    "pyvtk.DataSetAttr",
    "scipy",
    "scipy.constants",
    "scipy.spatial",
    "scipy.spatial.transform",
    "skip",
    "test_data",
    "common",
]
ignore_missing_imports = true
